### ISSUE TITLE
typo in command?

### ISSUE THREAD

**Issue by squillace** [chanezon/azure-linux#18]
Patrick, https://github.com/docker/machine has the command as **docker-machine create -d azure --azure-subscription-id="SUB_ID" --azure-subscription-cert="mycert.pem"**

but you have it as "machine":

**$ machine create -d azure \
--azure-subscription-id="9b5910a1-...-8e79d5ea2841" \
--azure-subscription-cert="azure-cert.pem" \
pat-1**

Typo, or was there something else about the way you did it that made it different?

**Comment by chanezon** [comment]
Thanks @squillace good catch. In the initial version you had to build, it was called machine.
I fixed the doc https://github.com/chanezon/azure-linux/commit/e46e4f4308111ef9461b9d1536f968c7103191b1
